### ISSUE TITLE
求其他lager数据集

### ISSUE THREAD

**Issue by yuziran123** [wangsiwei2010/awesome-multi-view-clustering#17]
您好，师兄，有其他的large数据集吗？可以直接用于多视图聚类的。CIFAR100，VGGFACE_50，VGGFACE_100，YTF_10,YTF_20等等，求师兄分享，谢谢！

**Comment by suye-wxy** [comment]
您好，YTF-10 YTF-20 YTF-50 YTF-100这些大规模数据集您方便分享吗？这是我的邮箱1147306975@qq.com感谢！

**Comment by yuziran123** [comment]
dataset:
https://www.dropbox.com/scl/fo/cznvjwkbpreowbdzjhemd/ALdK50aLjo2P_vbjJtDcx6k?rlkey=agbjoz9bhtmvwf4i105r3cdfs&amp;st=nz128r7o&amp;dl=0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangsiwei2010/awesome-multi-view-clustering"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月29日(星期五) 晚上8:14
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [wangsiwei2010/awesome-multi-view-clustering] 求其他lager数据集 (Issue #17)





 
您好，YTF-10 YTF-20 YTF-50 ***@***.***感谢！

**Comment by suye-wxy** [comment]
感谢您的分享！

**Comment by suye-wxy** [comment]
感谢您的分享！




suye
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangsiwei2010/awesome-multi-view-clustering"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月29日(星期五) 晚上8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangsiwei2010/awesome-multi-view-clustering] 求其他lager数据集 (Issue #17)





 dataset: 
 https://www.dropbox.com/scl/fo/cznvjwkbpreowbdzjhemd/ALdK50aLjo2P_vbjJtDcx6k?rlkey=agbjoz9bhtmvwf4i105r3cdfs&amp;amp;st=nz128r7o&amp;amp;dl=0 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "wangsiwei2010/awesome-multi-view-clustering"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年11月29日(星期五) 晚上8:14 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [wangsiwei2010/awesome-multi-view-clustering] 求其他lager数据集 (Issue #17) 
 
 
 
 
 
   
 您好，YTF-10 YTF-20 YTF-50 ***@***.***感谢！

**Comment by MrHUA1712** [comment]
您好，大规模数据集YTF-10 YTF-20 YTF-50 YTF-100这些，方便可以再分享一下吗，这是我的邮箱”qianyaoqiang1@gmail.com“
