### ISSUE TITLE
关于Multiview Clustering: A Scalable and Parameter-Free Bipartite Graph Fusion Method的代码问题

### ISSUE THREAD

**Issue by YyHEAN** [wangsiwei2010/awesome-multi-view-clustering#18]
在Multiview Clustering: A Scalable and Parameter-Free Bipartite Graph Fusion Method这篇文章的代码中
coclustering bipartite fast1.m这个代码的188行，
[clusternum,y]=graphconncomp(SS0);
其中的graphconncomp() 函数并没有给出定义
导致在复现代码时会产生报错，应当是缺少了相关的定义函数
请问是否有包含这个函数的代码文件

**Comment by YyHEAN** [comment]
发现Matlab 22b 之后的版本删除了graphconncomp函数 转而用conncomp函数替换，问题解决了

**Comment by haoya-alla** [comment]
你好，请问在哪儿找到的这篇文章的源码？
