### ISSUE TITLE
代码与论文不匹配的问题

### ISSUE THREAD

**Issue by LSC-getup** [wangsiwei2010/awesome-multi-view-clustering#6]
在Scalable Multi-view Clustering中
TPAMI 2021: Multi-view Clustering: A Scalable and Parameter-free Bipartite Graph Fusion Method
这篇TPAMI的代码是AAAI20: Large-scale Multi-view Subspace Clustering in Linear Time 的。这篇TPAMI的代码我也暂时没找到，尴尬

而AAAI20: Large-scale Multi-view Subspace Clustering in Linear Time这篇论文的代码是后面ACM MM2021: Scalable Multi-view Subspace Clustering with Unified Anchors 的。

同时，AAAI20: Large-scale Multi-view Subspace Clustering in Linear Time 这个文章标题的large拼写少了一个L。

**Comment by wangsiwei2010** [comment]
您好，很抱歉当时没有仔细核对。现在这两篇文章的相应代码已更新，请核对。

**Comment by wangsiwei2010** [comment]
您好，很抱歉当时没有仔细核对。现在这两篇文章的相应代码已更新，请核对。

**Comment by wangsiwei2010** [comment]
您好，很抱歉当时没有仔细核对。现在这两篇文章的相应代码已更新，请核对。

**Comment by LSC-getup** [comment]
您的速度真快啊，感谢您的工作为我们的研究提供了巨大的便利！不过我刚才尝试查看TPAMI 2021: Multi-view Clustering: A Scalable and Parameter-free Bipartite Graph Fusion Method 这篇论文的代码的时候发现需要百度网盘的提取码，请问方便提供一下吗？

**Comment by LSC-getup** [comment]
感谢您的工作为我们的研究提供了巨大的便利！

**Comment by wangsiwei2010** [comment]
您好，提取码在条目code的右边，请获取。fvnh

**Comment by wangsiwei2010** [comment]
麻烦您有空时close此issue. 此issue目前已被解决。
